name: minigpu_example
description: Demonstrates how to use the minigpu package.
version: 1.0.0
publish_to: none

#####

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  minigpu:
    path: ../
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

#####

flutter:
  uses-material-design: true

  assets:
    - assets/hello.shader
