name: gpu_tensor
description: A comprehensive GPU tensor library for Dart and Flutter, designed to leverage the power of webgpu across platforms for efficient tensor operations.
version: 1.0.1
repository: https://github.com/PracticalXR/minigpu/tree/main/gpu_tensor
publish_to: none


environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  minigpu:
    path: ../minigpu

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0


###

platforms:
  windows:
  android:
  linux:
  ios:
  macos:
  web:
