// ignore_for_file: camel_case_types
// ignore_for_file: prefer_double_quotes
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: constant_identifier_names
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: sort_constructors_first
// ignore_for_file: unused_element

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Void Function()>()
external void mgpuInitializeContext();

@ffi.Native<ffi.Void Function(MGPUCallback)>()
external void mgpuInitializeContextAsync(
  MGPUCallback callback,
);

@ffi.Native<ffi.Void Function()>()
external void mgpuDestroyContext();

@ffi.Native<ffi.Pointer<MGPUComputeShader> Function()>()
external ffi.Pointer<MGPUComputeShader> mgpuCreateComputeShader();

@ffi.Native<ffi.Void Function(ffi.Pointer<MGPUComputeShader>)>()
external void mgpuDestroyComputeShader(
  ffi.Pointer<MGPUComputeShader> shader,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<MGPUComputeShader>, ffi.Pointer<ffi.Char>)>()
external void mgpuLoadKernel(
  ffi.Pointer<MGPUComputeShader> shader,
  ffi.Pointer<ffi.Char> kernelString,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<MGPUComputeShader>)>()
external int mgpuHasKernel(
  ffi.Pointer<MGPUComputeShader> shader,
);

@ffi.Native<ffi.Pointer<MGPUBuffer> Function(ffi.Int, ffi.Int)>()
external ffi.Pointer<MGPUBuffer> mgpuCreateBuffer(
  int bufferSize,
  int dataType,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<MGPUBuffer>)>()
external void mgpuDestroyBuffer(
  ffi.Pointer<MGPUBuffer> buffer,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<MGPUComputeShader>, ffi.Int, ffi.Pointer<MGPUBuffer>)>()
external void mgpuSetBuffer(
  ffi.Pointer<MGPUComputeShader> shader,
  int tag,
  ffi.Pointer<MGPUBuffer> buffer,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<MGPUComputeShader>, ffi.Int, ffi.Int, ffi.Int)>()
external void mgpuDispatch(
  ffi.Pointer<MGPUComputeShader> shader,
  int groupsX,
  int groupsY,
  int groupsZ,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<MGPUComputeShader>, ffi.Int, ffi.Int, ffi.Int,
        MGPUCallback)>()
external void mgpuDispatchAsync(
  ffi.Pointer<MGPUComputeShader> shader,
  int groupsX,
  int groupsY,
  int groupsZ,
  MGPUCallback callback,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Void>, ffi.Size, ffi.Size)>()
external void mgpuReadBufferSync(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Void> outputData,
  int size,
  int offset,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Int8>, ffi.Size,
        ffi.Size, MGPUCallback)>()
external void mgpuReadBufferAsyncInt8(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Int8> outputData,
  int size,
  int offset,
  MGPUCallback callback,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Int16>, ffi.Size,
        ffi.Size, MGPUCallback)>()
external void mgpuReadBufferAsyncInt16(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Int16> outputData,
  int size,
  int offset,
  MGPUCallback callback,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Int32>, ffi.Size,
        ffi.Size, MGPUCallback)>()
external void mgpuReadBufferAsyncInt32(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Int32> outputData,
  int size,
  int offset,
  MGPUCallback callback,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Int64>, ffi.Size,
        ffi.Size, MGPUCallback)>()
external void mgpuReadBufferAsyncInt64(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Int64> outputData,
  int size,
  int offset,
  MGPUCallback callback,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Uint8>, ffi.Size,
        ffi.Size, MGPUCallback)>()
external void mgpuReadBufferAsyncUint8(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Uint8> outputData,
  int size,
  int offset,
  MGPUCallback callback,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Uint16>,
        ffi.Size, ffi.Size, MGPUCallback)>()
external void mgpuReadBufferAsyncUint16(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Uint16> outputData,
  int size,
  int offset,
  MGPUCallback callback,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Uint32>,
        ffi.Size, ffi.Size, MGPUCallback)>()
external void mgpuReadBufferAsyncUint32(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Uint32> outputData,
  int size,
  int offset,
  MGPUCallback callback,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Uint64>,
        ffi.Size, ffi.Size, MGPUCallback)>()
external void mgpuReadBufferAsyncUint64(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Uint64> outputData,
  int size,
  int offset,
  MGPUCallback callback,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Float>, ffi.Size,
        ffi.Size, MGPUCallback)>()
external void mgpuReadBufferAsyncFloat(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Float> outputData,
  int size,
  int offset,
  MGPUCallback callback,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Double>,
        ffi.Size, ffi.Size, MGPUCallback)>()
external void mgpuReadBufferAsyncDouble(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Double> outputData,
  int size,
  int offset,
  MGPUCallback callback,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Int8>, ffi.Size)>()
external void mgpuSetBufferDataInt8(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Int8> inputData,
  int byteSize,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Int16>, ffi.Size)>()
external void mgpuSetBufferDataInt16(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Int16> inputData,
  int byteSize,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Int32>, ffi.Size)>()
external void mgpuSetBufferDataInt32(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Int32> inputData,
  int byteSize,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Int64>, ffi.Size)>()
external void mgpuSetBufferDataInt64(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Int64> inputData,
  int byteSize,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Uint8>, ffi.Size)>()
external void mgpuSetBufferDataUint8(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Uint8> inputData,
  int byteSize,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Uint16>, ffi.Size)>()
external void mgpuSetBufferDataUint16(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Uint16> inputData,
  int byteSize,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Uint32>, ffi.Size)>()
external void mgpuSetBufferDataUint32(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Uint32> inputData,
  int byteSize,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Uint64>, ffi.Size)>()
external void mgpuSetBufferDataUint64(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Uint64> inputData,
  int byteSize,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Float>, ffi.Size)>()
external void mgpuSetBufferDataFloat(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Float> inputData,
  int byteSize,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<MGPUBuffer>, ffi.Pointer<ffi.Double>, ffi.Size)>()
external void mgpuSetBufferDataDouble(
  ffi.Pointer<MGPUBuffer> buffer,
  ffi.Pointer<ffi.Double> inputData,
  int byteSize,
);

final class MGPUComputeShader extends ffi.Opaque {}

final class MGPUBuffer extends ffi.Opaque {}

typedef MGPUCallbackFunction = ffi.Void Function();
typedef DartMGPUCallbackFunction = void Function();
typedef MGPUCallback = ffi.Pointer<ffi.NativeFunction<MGPUCallbackFunction>>;
